### ISSUE TITLE
Max attempts error

### ISSUE THREAD

**Issue by brunoinds** [JoJoBond/Powershell-YouTube-Upload#7] opened 2020-07-27 20:18 UTC
I'm using all the recommended commands. The OAuth screen appears and logs in successfully.
This is the command I'm executing in PowerShell terminal:

`Add-YouTube-Video -File "..\teta.mp4" -Title "title" -CategoryID 22 -Description "description" -PrivacyStatus "unlisted" -LocationDescription "location, area" -RecordingDate 2020-07-01`

and returns sunddelly:

`YouTube upload canceled after 5 attempts`

**Important things to consider:**
1. OAuth is OK
2. File location is OK
3. Internet and Firewall is OK

Any ideas?
Thanks! Great script!

**Comment by JoJoBond** [comment] 2020-07-27 20:20
Please check your API key and quotas. If the problems persists, I will take a look tomorrow.

**Comment by ulfwuestefeld** [comment] 2020-10-17 14:09
It seems that the max attempts error is caused by another error coming from the youtubecli.exe

```
C:\YouTube-Upload\YoutubeCLI.exe -Mode Video -Operation Add -File "2020-09-30_02-56-32.AVI" -Title "2020-09-30 02:56:32" -PrivacyStatus unlisted -RecordingDate "2020-09-30" -CategoryID 15
YouTube CLI
===========
Logging in.
Login OK.
Selected file: 2020-09-30_02-56-32.AVI
File size: 24259264
Error: Positive number required.
Parameter name: bufferSize
```

**Comment by JoJoBond** [comment] 2020-10-17 15:26
I think I found the issue. Please checkout commit 0d39e8f0ba2c97711f7cd84bdfefe6b193d33f82 and report back.

**Comment by ulfwuestefeld** [comment] 2020-10-18 09:13
> I think I found the issue. Please checkout commit [0d39e8f](https://github.com/JoJoBond/Powershell-YouTube-Upload/commit/0d39e8f0ba2c97711f7cd84bdfefe6b193d33f82) and report back.

Works like a charm. Thanks for fixing it.

**Comment by JoJoBond** [comment] 2020-10-18 09:48
Excellent. I'll close this issue. Please open a new issue if it re-appears.

**Closed as completed by JoJoBond** 2020-10-18 09:48 UTC
